### ISSUE TITLE
Unable to save file

### ISSUE THREAD

**Issue by thvardhan** [wwwtyro/space-3d#4]
I am unable to find the download/save button for the texture.
I think it was removed from the html.
for the time being I am using 
`var canvas = document.getElementById("texture-canvas");
var img    = canvas.toDataURL("image/png");
document.write('<img src="'+img+'"/>');`
in console and saving it manually. Please do this problem

**Comment by ghost** [comment]
You could make a PR if you want to. This is not a problem for me.

**Comment by thvardhan** [comment]
it seems the issue has been fixed. Thanks.
